### ISSUE TITLE
Need for refreshing the page after saving links before we can start using it from the context menus

### ISSUE THREAD

**Issue by sahildua2305** [sahildua2305/easy-paste-chrome#1]

**Comment by nirajkaushal** [comment]
It's working

**Comment by sahildua2305** [comment]
@nirajkaushal Sorry for not making it clear in the issue that it was an issue when I was trying out dynamic context menus (the version in which some of the context menus can be removed or some new ones can be added dynamically). This version with statically created context menus is a stable one and free from this issue.
